"""
Seed data for Sri Lankan suburbs, CBSL 13 Divisional Secretariats, and market benchmarks.
"""
from decimal import Decimal
import structlog
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.suburb import Suburb

logger = structlog.get_logger(__name__)

# Colombo Suburb Tiers and CBSL Divisional Secretariats Benchmarks
# Land is per perch (LKR), Apartment is per sqft (LKR)
SEED_SUBURBS = [
    # --- PRIME COLOMBO (C1 - C15) ---
    {
        "name": "Colombo 1",
        "slug": "colombo-1",
        "district": "Colombo",
        "ds_division": "Colombo",
        "tier": "Prime Colombo",
        "aliases": ["Fort", "Colombo Fort", "colombo 01"],
        "baseline_land_perch_min": Decimal("15000000"),
        "baseline_land_perch_max": Decimal("25000000"),
        "baseline_apartment_sqft_min": Decimal("65000"),
        "baseline_apartment_sqft_max": Decimal("120000"),
    },
    {
        "name": "Colombo 2",
        "slug": "colombo-2",
        "district": "Colombo",
        "ds_division": "Colombo",
        "tier": "Prime Colombo",
        "aliases": ["Slave Island", "Kompanna Veediya", "Union Place", "colombo 02"],
        "baseline_land_perch_min": Decimal("14000000"),
        "baseline_land_perch_max": Decimal("22000000"),
        "baseline_apartment_sqft_min": Decimal("60000"),
        "baseline_apartment_sqft_max": Decimal("110000"),
    },
    {
        "name": "Colombo 3",
        "slug": "colombo-3",
        "district": "Colombo",
        "ds_division": "Colombo",
        "tier": "Prime Colombo",
        "aliases": ["Kollupitiya", "Colpetty", "colombo 03"],
        "baseline_land_perch_min": Decimal("16000000"),
        "baseline_land_perch_max": Decimal("25000000"),
        "baseline_apartment_sqft_min": Decimal("60000"),
        "baseline_apartment_sqft_max": Decimal("125000"),
    },
    {
        "name": "Colombo 4",
        "slug": "colombo-4",
        "district": "Colombo",
        "ds_division": "Thimbirigasyaya",
        "tier": "Prime Colombo",
        "aliases": ["Bambalapitiya", "colombo 04"],
        "baseline_land_perch_min": Decimal("14000000"),
        "baseline_land_perch_max": Decimal("22000000"),
        "baseline_apartment_sqft_min": Decimal("55000"),
        "baseline_apartment_sqft_max": Decimal("100000"),
    },
    {
        "name": "Colombo 5",
        "slug": "colombo-5",
        "district": "Colombo",
        "ds_division": "Thimbirigasyaya",
        "tier": "Prime Colombo",
        "aliases": ["Havelock Town", "Havelock City", "Kirulapone", "Narahenpita", "colombo 05"],
        "baseline_land_perch_min": Decimal("12000000"),
        "baseline_land_perch_max": Decimal("18000000"),
        "baseline_apartment_sqft_min": Decimal("50000"),
        "baseline_apartment_sqft_max": Decimal("85000"),
    },
    {
        "name": "Colombo 6",
        "slug": "colombo-6",
        "district": "Colombo",
        "ds_division": "Thimbirigasyaya",
        "tier": "Prime Colombo",
        "aliases": ["Wellawatte", "Wellawatta", "Pamankada", "colombo 06"],
        "baseline_land_perch_min": Decimal("9000000"),
        "baseline_land_perch_max": Decimal("15000000"),
        "baseline_apartment_sqft_min": Decimal("40000"),
        "baseline_apartment_sqft_max": Decimal("75000"),
    },
    {
        "name": "Colombo 7",
        "slug": "colombo-7",
        "district": "Colombo",
        "ds_division": "Thimbirigasyaya",
        "tier": "Prime Colombo",
        "aliases": ["Cinnamon Gardens", "colombo 07"],
        "baseline_land_perch_min": Decimal("18000000"),
        "baseline_land_perch_max": Decimal("30000000"),
        "baseline_apartment_sqft_min": Decimal("70000"),
        "baseline_apartment_sqft_max": Decimal("130000"),
    },
    {
        "name": "Colombo 8",
        "slug": "colombo-8",
        "district": "Colombo",
        "ds_division": "Colombo",
        "tier": "Prime Colombo",
        "aliases": ["Borella", "colombo 08"],
        "baseline_land_perch_min": Decimal("8000000"),
        "baseline_land_perch_max": Decimal("14000000"),
        "baseline_apartment_sqft_min": Decimal("38000"),
        "baseline_apartment_sqft_max": Decimal("65000"),
    },
    {
        "name": "Colombo 9",
        "slug": "colombo-9",
        "district": "Colombo",
        "ds_division": "Colombo",
        "tier": "Prime Colombo",
        "aliases": ["Dematagoda", "colombo 09"],
        "baseline_land_perch_min": Decimal("5500000"),
        "baseline_land_perch_max": Decimal("9000000"),
        "baseline_apartment_sqft_min": Decimal("30000"),
        "baseline_apartment_sqft_max": Decimal("50000"),
    },
    {
        "name": "Colombo 10",
        "slug": "colombo-10",
        "district": "Colombo",
        "ds_division": "Colombo",
        "tier": "Prime Colombo",
        "aliases": ["Maradana", "Panchikawatte", "colombo 10"],
        "baseline_land_perch_min": Decimal("6500000"),
        "baseline_land_perch_max": Decimal("11000000"),
        "baseline_apartment_sqft_min": Decimal("32000"),
        "baseline_apartment_sqft_max": Decimal("55000"),
    },

    # --- INNER AFFLUENT SUBURBS ---
    {
        "name": "Rajagiriya",
        "slug": "rajagiriya",
        "district": "Colombo",
        "ds_division": "Sri Jayawardenepura Kotte",
        "tier": "Inner Suburbs (Affluent)",
        "aliases": ["Obeysekerapura", "Kalapaluwawa"],
        "baseline_land_perch_min": Decimal("4500000"),
        "baseline_land_perch_max": Decimal("7500000"),
        "baseline_apartment_sqft_min": Decimal("38000"),
        "baseline_apartment_sqft_max": Decimal("65000"),
    },
    {
        "name": "Nawala",
        "slug": "nawala",
        "district": "Colombo",
        "ds_division": "Sri Jayawardenepura Kotte",
        "tier": "Inner Suburbs (Affluent)",
        "aliases": ["Koswatte Nawala"],
        "baseline_land_perch_min": Decimal("4500000"),
        "baseline_land_perch_max": Decimal("7000000"),
        "baseline_apartment_sqft_min": Decimal("35000"),
        "baseline_apartment_sqft_max": Decimal("58000"),
    },
    {
        "name": "Battaramulla",
        "slug": "battaramulla",
        "district": "Colombo",
        "ds_division": "Kaduwela",
        "tier": "Inner Suburbs (Affluent)",
        "aliases": ["Koswatte Battaramulla"],
        "baseline_land_perch_min": Decimal("3500000"),
        "baseline_land_perch_max": Decimal("5500000"),
        "baseline_apartment_sqft_min": Decimal("32000"),
        "baseline_apartment_sqft_max": Decimal("50000"),
    },
    {
        "name": "Pelawatte",
        "slug": "pelawatte",
        "district": "Colombo",
        "ds_division": "Kaduwela",
        "tier": "Inner Suburbs (Affluent)",
        "aliases": ["Pelawatta"],
        "baseline_land_perch_min": Decimal("4000000"),
        "baseline_land_perch_max": Decimal("6500000"),
        "baseline_apartment_sqft_min": Decimal("35000"),
        "baseline_apartment_sqft_max": Decimal("55000"),
    },
    {
        "name": "Kotte",
        "slug": "kotte",
        "district": "Colombo",
        "ds_division": "Sri Jayawardenepura Kotte",
        "tier": "Inner Suburbs (Affluent)",
        "aliases": ["Ethul Kotte", "Pita Kotte", "Sri Jayawardenepura Kotte"],
        "baseline_land_perch_min": Decimal("3500000"),
        "baseline_land_perch_max": Decimal("5500000"),
        "baseline_apartment_sqft_min": Decimal("30000"),
        "baseline_apartment_sqft_max": Decimal("50000"),
    },

    # --- SOUTHERN COASTAL BELT ---
    {
        "name": "Dehiwala",
        "slug": "dehiwala",
        "district": "Colombo",
        "ds_division": "Dehiwala",
        "tier": "Southern Coastal",
        "aliases": ["Dehiwela", "Kalubowila", "Nedimala", "Kohuwala Dehiwala"],
        "baseline_land_perch_min": Decimal("3500000"),
        "baseline_land_perch_max": Decimal("6000000"),
        "baseline_apartment_sqft_min": Decimal("32000"),
        "baseline_apartment_sqft_max": Decimal("52000"),
    },
    {
        "name": "Mount Lavinia",
        "slug": "mount-lavinia",
        "district": "Colombo",
        "ds_division": "Dehiwala",
        "tier": "Southern Coastal",
        "aliases": ["Mt Lavinia", "Mt. Lavinia", "Galkissa"],
        "baseline_land_perch_min": Decimal("3200000"),
        "baseline_land_perch_max": Decimal("5500000"),
        "baseline_apartment_sqft_min": Decimal("30000"),
        "baseline_apartment_sqft_max": Decimal("50000"),
    },
    {
        "name": "Ratmalana",
        "slug": "ratmalana",
        "district": "Colombo",
        "ds_division": "Ratmalana",
        "tier": "Southern Coastal",
        "aliases": ["Attidiya", "Kandawala"],
        "baseline_land_perch_min": Decimal("2500000"),
        "baseline_land_perch_max": Decimal("4200000"),
        "baseline_apartment_sqft_min": Decimal("26000"),
        "baseline_apartment_sqft_max": Decimal("42000"),
    },
    {
        "name": "Moratuwa",
        "slug": "moratuwa",
        "district": "Colombo",
        "ds_division": "Moratuwa",
        "tier": "Southern Coastal",
        "aliases": ["Rawathawatte", "Katubedda", "Lunawa", "Moratumulla", "Angulana"],
        "baseline_land_perch_min": Decimal("1800000"),
        "baseline_land_perch_max": Decimal("3200000"),
        "baseline_apartment_sqft_min": Decimal("22000"),
        "baseline_apartment_sqft_max": Decimal("36000"),
    },

    # --- HIGH LEVEL & EAST CORRIDOR ---
    {
        "name": "Nugegoda",
        "slug": "nugegoda",
        "district": "Colombo",
        "ds_division": "Sri Jayawardenepura Kotte",
        "tier": "High Level / East Corridor",
        "aliases": ["Mirihana", "Embuldeniya", "Jubilee Post", "Gangodawila"],
        "baseline_land_perch_min": Decimal("3800000"),
        "baseline_land_perch_max": Decimal("5800000"),
        "baseline_apartment_sqft_min": Decimal("32000"),
        "baseline_apartment_sqft_max": Decimal("48000"),
    },
    {
        "name": "Kohuwala",
        "slug": "kohuwala",
        "district": "Colombo",
        "ds_division": "Dehiwala",
        "tier": "High Level / East Corridor",
        "aliases": ["Kohuwela"],
        "baseline_land_perch_min": Decimal("3500000"),
        "baseline_land_perch_max": Decimal("5200000"),
        "baseline_apartment_sqft_min": Decimal("30000"),
        "baseline_apartment_sqft_max": Decimal("46000"),
    },
    {
        "name": "Maharagama",
        "slug": "maharagama",
        "district": "Colombo",
        "ds_division": "Maharagama",
        "tier": "High Level / East Corridor",
        "aliases": ["Navinna", "Pamunuwa", "Arawwala"],
        "baseline_land_perch_min": Decimal("2500000"),
        "baseline_land_perch_max": Decimal("4000000"),
        "baseline_apartment_sqft_min": Decimal("25000"),
        "baseline_apartment_sqft_max": Decimal("38000"),
    },
    {
        "name": "Boralesgamuwa",
        "slug": "boralesgamuwa",
        "district": "Colombo",
        "ds_division": "Kesbewa",
        "tier": "High Level / East Corridor",
        "aliases": ["Bokundara", "Bellanwila", "Rattanapitiya"],
        "baseline_land_perch_min": Decimal("2600000"),
        "baseline_land_perch_max": Decimal("4200000"),
        "baseline_apartment_sqft_min": Decimal("26000"),
        "baseline_apartment_sqft_max": Decimal("40000"),
    },

    # --- RAPID GROWTH & TECH CORRIDOR ---
    {
        "name": "Malabe",
        "slug": "malabe",
        "district": "Colombo",
        "ds_division": "Kaduwela",
        "tier": "Rapid Growth Suburbs",
        "aliases": ["Thalahena", "Arangala", "Pittugala", "Kahanthota"],
        "baseline_land_perch_min": Decimal("1800000"),
        "baseline_land_perch_max": Decimal("3200000"),
        "baseline_apartment_sqft_min": Decimal("25000"),
        "baseline_apartment_sqft_max": Decimal("40000"),
    },
    {
        "name": "Thalawathugoda",
        "slug": "thalawathugoda",
        "district": "Colombo",
        "ds_division": "Maharagama",
        "tier": "Rapid Growth Suburbs",
        "aliases": ["Talawatugoda", "Kalalgoda", "Madiwela", "Hokandara Road"],
        "baseline_land_perch_min": Decimal("2800000"),
        "baseline_land_perch_max": Decimal("4500000"),
        "baseline_apartment_sqft_min": Decimal("28000"),
        "baseline_apartment_sqft_max": Decimal("45000"),
    },
    {
        "name": "Hokandara",
        "slug": "hokandara",
        "district": "Colombo",
        "ds_division": "Maharagama",
        "tier": "Rapid Growth Suburbs",
        "aliases": ["Hokandara North", "Hokandara South"],
        "baseline_land_perch_min": Decimal("1600000"),
        "baseline_land_perch_max": Decimal("2800000"),
        "baseline_apartment_sqft_min": Decimal("24000"),
        "baseline_apartment_sqft_max": Decimal("36000"),
    },
    {
        "name": "Athurugiriya",
        "slug": "athurugiriya",
        "district": "Colombo",
        "ds_division": "Kaduwela",
        "tier": "Rapid Growth Suburbs",
        "aliases": ["Millennium City", "Oruwala"],
        "baseline_land_perch_min": Decimal("1300000"),
        "baseline_land_perch_max": Decimal("2400000"),
        "baseline_apartment_sqft_min": Decimal("22000"),
        "baseline_apartment_sqft_max": Decimal("34000"),
    },

    # --- OUTER COMMUTER BELT ---
    {
        "name": "Kottawa",
        "slug": "kottawa",
        "district": "Colombo",
        "ds_division": "Maharagama",
        "tier": "Outer Commuter Belt",
        "aliases": ["Pannipitiya", "Rukmalgama", "Makumbura"],
        "baseline_land_perch_min": Decimal("1600000"),
        "baseline_land_perch_max": Decimal("2800000"),
        "baseline_apartment_sqft_min": Decimal("22000"),
        "baseline_apartment_sqft_max": Decimal("35000"),
    },
    {
        "name": "Piliyandala",
        "slug": "piliyandala",
        "district": "Colombo",
        "ds_division": "Kesbewa",
        "tier": "Outer Commuter Belt",
        "aliases": ["Kesbewa", "Madapatha", "Kahathuduwa", "Polgasowita"],
        "baseline_land_perch_min": Decimal("1400000"),
        "baseline_land_perch_max": Decimal("2400000"),
        "baseline_apartment_sqft_min": Decimal("20000"),
        "baseline_apartment_sqft_max": Decimal("32000"),
    },
    {
        "name": "Homagama",
        "slug": "homagama",
        "district": "Colombo",
        "ds_division": "Homagama",
        "tier": "Outer Commuter Belt",
        "aliases": ["Meegoda", "Godagama", "Pitipana"],
        "baseline_land_perch_min": Decimal("900000"),
        "baseline_land_perch_max": Decimal("1800000"),
        "baseline_apartment_sqft_min": Decimal("18000"),
        "baseline_apartment_sqft_max": Decimal("28000"),
    },
    {
        "name": "Kaduwela",
        "slug": "kaduwela",
        "district": "Colombo",
        "ds_division": "Kaduwela",
        "tier": "Outer Commuter Belt",
        "aliases": ["Ranala", "Nawagamuwa", "Welesara"],
        "baseline_land_perch_min": Decimal("1100000"),
        "baseline_land_perch_max": Decimal("2000000"),
        "baseline_apartment_sqft_min": Decimal("18000"),
        "baseline_apartment_sqft_max": Decimal("30000"),
    },

    # --- GAMPAHA METRO HUBS ---
    {
        "name": "Wattala",
        "slug": "wattala",
        "district": "Gampaha",
        "ds_division": "Wattala",
        "tier": "Gampaha Metro",
        "aliases": ["Hendala", "Mabola", "Peliyagoda"],
        "baseline_land_perch_min": Decimal("2000000"),
        "baseline_land_perch_max": Decimal("3800000"),
        "baseline_apartment_sqft_min": Decimal("24000"),
        "baseline_apartment_sqft_max": Decimal("38000"),
    },
    {
        "name": "Ja-Ela",
        "slug": "ja-ela",
        "district": "Gampaha",
        "ds_division": "Ja-Ela",
        "tier": "Gampaha Metro",
        "aliases": ["Ja Ela", "Kandana", "Ekala"],
        "baseline_land_perch_min": Decimal("1400000"),
        "baseline_land_perch_max": Decimal("2600000"),
        "baseline_apartment_sqft_min": Decimal("20000"),
        "baseline_apartment_sqft_max": Decimal("34000"),
    },
    {
        "name": "Kadawatha",
        "slug": "kadawatha",
        "district": "Gampaha",
        "ds_division": "Mahara",
        "tier": "Gampaha Metro",
        "aliases": ["Kirillawala", "Eldeniya", "Ranmuthugala"],
        "baseline_land_perch_min": Decimal("1200000"),
        "baseline_land_perch_max": Decimal("2200000"),
        "baseline_apartment_sqft_min": Decimal("18000"),
        "baseline_apartment_sqft_max": Decimal("30000"),
    },
    {
        "name": "Kiribathgoda",
        "slug": "kiribathgoda",
        "district": "Gampaha",
        "ds_division": "Kelaniya",
        "tier": "Gampaha Metro",
        "aliases": ["Kelaniya", "Dalugama"],
        "baseline_land_perch_min": Decimal("2200000"),
        "baseline_land_perch_max": Decimal("3800000"),
        "baseline_apartment_sqft_min": Decimal("22000"),
        "baseline_apartment_sqft_max": Decimal("35000"),
    },
    {
        "name": "Negombo",
        "slug": "negombo",
        "district": "Gampaha",
        "ds_division": "Negombo",
        "tier": "Coastal Tourism & Hub",
        "aliases": ["Katunayake", "Kochchikade", "Daluwakotuwa"],
        "baseline_land_perch_min": Decimal("1200000"),
        "baseline_land_perch_max": Decimal("2800000"),
        "baseline_apartment_sqft_min": Decimal("22000"),
        "baseline_apartment_sqft_max": Decimal("40000"),
    },
]


def seed_suburbs_data(db: Session) -> int:
    """Inserts or updates initial suburb reference data."""
    seeded = 0
    for item in SEED_SUBURBS:
        stmt = select(Suburb).where((Suburb.name == item["name"]) | (Suburb.slug == item["slug"]))
        existing = db.execute(stmt).scalar_one_or_none()
        if existing:
            # Update baseline benchmarks if present
            existing.tier = item["tier"]
            existing.ds_division = item["ds_division"]
            existing.aliases = item["aliases"]
            existing.baseline_land_perch_min = item["baseline_land_perch_min"]
            existing.baseline_land_perch_max = item["baseline_land_perch_max"]
            existing.baseline_apartment_sqft_min = item["baseline_apartment_sqft_min"]
            existing.baseline_apartment_sqft_max = item["baseline_apartment_sqft_max"]
        else:
            sub = Suburb(
                name=item["name"],
                slug=item["slug"],
                district=item["district"],
                ds_division=item["ds_division"],
                tier=item["tier"],
                aliases=item["aliases"],
                baseline_land_perch_min=item["baseline_land_perch_min"],
                baseline_land_perch_max=item["baseline_land_perch_max"],
                baseline_apartment_sqft_min=item["baseline_apartment_sqft_min"],
                baseline_apartment_sqft_max=item["baseline_apartment_sqft_max"],
            )
            db.add(sub)
            seeded += 1

    db.commit()
    logger.info("seeded_suburbs_completed", new_seeded=seeded, total=len(SEED_SUBURBS))
    return seeded
