"""
Ikman location hierarchy and slug resolution.
Maps location keywords, suburbs, and postal zones to Ikman's native location slugs.
"""
from typing import Optional

# Common aliases, misspellings, and Colombo postal zones
IKMAN_LOCATION_ALIASES: dict[str, str] = {
    # Variations & misspellings
    "dehiwela": "dehiwala",
    "mt lavinia": "mount-lavinia",
    "mt. lavinia": "mount-lavinia",
    "mount lavinia": "mount-lavinia",
    "thalawathugoda": "talawatugoda",
    "talawathugoda": "talawatugoda",
    "kohuwela": "kohuwala",
    "ja ela": "ja-ela",
    "hali ela": "hali-ela",
    "higurakgoda": "hingurakgoda",

    # Colombo Postal Districts & Neighborhoods
    "colombo 01": "colombo-1",
    "colombo 02": "colombo-2",
    "colombo 03": "colombo-3",
    "colombo 04": "colombo-4",
    "colombo 05": "colombo-5",
    "colombo 06": "colombo-6",
    "colombo 07": "colombo-7",
    "colombo 08": "colombo-8",
    "colombo 09": "colombo-9",
    "colombo 1": "colombo-1",
    "colombo 2": "colombo-2",
    "colombo 3": "colombo-3",
    "colombo 4": "colombo-4",
    "colombo 5": "colombo-5",
    "colombo 6": "colombo-6",
    "colombo 7": "colombo-7",
    "colombo 8": "colombo-8",
    "colombo 9": "colombo-9",
    "colombo 10": "colombo-10",
    "colombo 11": "colombo-11",
    "colombo 12": "colombo-12",
    "colombo 13": "colombo-13",
    "colombo 14": "colombo-14",
    "colombo 15": "colombo-15",

    # Colombo postal zone aliases
    "fort": "colombo-1",
    "slave island": "colombo-2",
    "kollupitiya": "colombo-3",
    "colpetty": "colombo-3",
    "bambalapitiya": "colombo-4",
    "havelock town": "colombo-5",
    "havelock city": "colombo-5",
    "havelock": "colombo-5",
    "kirulapone": "colombo-5",
    "wellawatte": "colombo-6",
    "wellawatta": "colombo-6",
    "pamankada": "colombo-6",
    "cinnamon gardens": "colombo-7",
    "borella": "colombo-8",
    "dematagoda": "colombo-9",
    "maradana": "colombo-10",
    "panchikawatte": "colombo-10",
    "pettah": "colombo-11",
    "hultsdorf": "colombo-12",
    "kotahena": "colombo-13",
    "kochchikade": "colombo-13",
    "grandpass": "colombo-14",
    "mutwal": "colombo-15",
    "modara": "colombo-15",
    "mattakkuliya": "colombo-15",
}

# Complete Ikman native location slugs
IKMAN_LOCATIONS: dict[str, str] = {
    "ampara": "ampara",
    "akkarepattu": "akkarepattu",
    "ampara city": "ampara-52",
    "ampara-52": "ampara-52",
    "kalmunai": "kalmunai",
    "sainthamaruthu": "sainthamaruthu",
    "pottuvil": "pottuvil",
    "arugam bay": "arugam-bay",
    "arugam-bay": "arugam-bay",
    "panama": "panama",
    "anuradhapura": "anuradhapura",
    "anuradhapura city": "anuradhapura-71",
    "anuradhapura-71": "anuradhapura-71",
    "galenbindunuwewa": "galenbindunuwewa",
    "galnewa": "galnewa",
    "lahugala": "lahugala",
    "komari": "komari",
    "dehiattakandiya": "dehiattakandiya",
    "diyawiddagama": "diyawiddagama",
    "kekirawa": "kekirawa",
    "mawanagama": "mawanagama",
    "medawachchiya": "medawachchiya",
    "mihintale": "mihintale",
    "nochchiyagama": "nochchiyagama",
    "talawa": "talawa",
    "tambuttegama": "tambuttegama",
    "badulla": "badulla",
    "badulla city": "badulla-81",
    "badulla-81": "badulla-81",
    "bandarawela": "bandarawela",
    "ella": "ella",
    "hali ela": "hali-ela",
    "hali-ela": "hali-ela",
    "haputale": "haputale",
    "mahiyanganaya": "mahiyanganaya",
    "passara": "passara",
    "welimada": "welimada",
    "batticaloa": "batticaloa",
    "rideemaliyadda": "rideemaliyadda",
    "batticaloa city": "batticaloa-51",
    "batticaloa-51": "batticaloa-51",
    "colombo": "colombo",
    "athurugiriya": "athurugiriya",
    "battaramulla": "battaramulla",
    "boralesgamuwa": "boralesgamuwa",
    "colombo 1": "colombo-1",
    "colombo-1": "colombo-1",
    "colombo 2": "colombo-2",
    "colombo-2": "colombo-2",
    "colombo 3": "colombo-3",
    "colombo-3": "colombo-3",
    "colombo 4": "colombo-4",
    "colombo-4": "colombo-4",
    "colombo 5": "colombo-5",
    "colombo-5": "colombo-5",
    "colombo 6": "colombo-6",
    "colombo-6": "colombo-6",
    "colombo 7": "colombo-7",
    "colombo-7": "colombo-7",
    "colombo 8": "colombo-8",
    "colombo-8": "colombo-8",
    "colombo 9": "colombo-9",
    "colombo-9": "colombo-9",
    "colombo 10": "colombo-10",
    "colombo-10": "colombo-10",
    "colombo 11": "colombo-11",
    "colombo-11": "colombo-11",
    "colombo 12": "colombo-12",
    "colombo-12": "colombo-12",
    "colombo 13": "colombo-13",
    "colombo-13": "colombo-13",
    "colombo 14": "colombo-14",
    "colombo-14": "colombo-14",
    "colombo 15": "colombo-15",
    "colombo-15": "colombo-15",
    "dehiwala": "dehiwala",
    "hanwella": "hanwella",
    "homagama": "homagama",
    "kaduwela": "kaduwela",
    "kesbewa": "kesbewa",
    "kolonnawa": "kolonnawa",
    "kottawa": "kottawa",
    "maharagama": "maharagama",
    "malabe": "malabe",
    "moratuwa": "moratuwa",
    "mount lavinia": "mount-lavinia",
    "mount-lavinia": "mount-lavinia",
    "nawala": "nawala",
    "nugegoda": "nugegoda",
    "padukka": "padukka",
    "pannipitiya": "pannipitiya",
    "piliyandala": "piliyandala",
    "rajagiriya": "rajagiriya",
    "ratmalana": "ratmalana",
    "galle": "galle",
    "ambalangoda": "ambalangoda",
    "baddegama": "baddegama",
    "bentota": "bentota",
    "elpitiya": "elpitiya",
    "hikkaduwa": "hikkaduwa",
    "gampaha": "gampaha",
    "divulapitiya": "divulapitiya",
    "gampaha city": "gampaha-12",
    "gampaha-12": "gampaha-12",
    "ja-ela": "ja-ela",
    "kelaniya": "kelaniya",
    "kiribathgoda": "kiribathgoda",
    "minuwangoda": "minuwangoda",
    "mirigama": "mirigama",
    "negombo": "negombo",
    "wattala": "wattala",
    "hambantota": "hambantota",
    "ambalantota": "ambalantota",
    "beliatta": "beliatta",
    "hambantota city": "hambantota-33",
    "hambantota-33": "hambantota-33",
    "peliyagoda": "peliyagoda",
    "bopitiya": "bopitiya",
    "mawaramandiya": "mawaramandiya",
    "delathura": "delathura",
    "tangalla": "tangalla",
    "tissamaharama": "tissamaharama",
    "jaffna": "jaffna",
    "chavakachcheri": "chavakachcheri",
    "jaffna city": "jaffna-41",
    "jaffna-41": "jaffna-41",
    "nallur": "nallur",
    "kalutara": "kalutara",
    "bandaragama": "bandaragama",
    "beruwala": "beruwala",
    "horana": "horana",
    "ingiriya": "ingiriya",
    "kalutara city": "kalutara-13",
    "kalutara-13": "kalutara-13",
    "matugama": "matugama",
    "panadura": "panadura",
    "wadduwa": "wadduwa",
    "kandy": "kandy",
    "akurana": "akurana",
    "ittapane": "ittapane",
    "polgampola": "polgampola",
    "uthumgama": "uthumgama",
    "pitipana": "pitipana",
    "kandy city": "kandy-21",
    "kandy-21": "kandy-21",
    "kundasale": "kundasale",
    "walallavita": "walallavita",
    "awittawa": "awittawa",
    "meegahathenna": "meegahathenna",
    "kevitiyagala": "kevitiyagala",
    "gonapola": "gonapola",
    "moragala": "moragala",
    "talagala": "talagala",
    "kegalle": "kegalle",
    "dehiowita": "dehiowita",
    "deraniyagala": "deraniyagala",
    "galigamuwa": "galigamuwa",
    "kegalle city": "kegalle-92",
    "kegalle-92": "kegalle-92",
    "mawanella": "mawanella",
    "rambukkana": "rambukkana",
    "ruwanwella": "ruwanwella",
    "warakapola": "warakapola",
    "yatiyantota": "yatiyantota",
    "kilinochchi": "kilinochchi",
    "hemmathagama": "hemmathagama",
    "dodammuluwa": "dodammuluwa",
    "kurunegala": "kurunegala",
    "alawwa": "alawwa",
    "bingiriya": "bingiriya",
    "galgamuwa": "galgamuwa",
    "ibbagamuwa": "ibbagamuwa",
    "kurunegala city": "kurunegala-61",
    "kurunegala-61": "kurunegala-61",
    "mawathagama": "mawathagama",
    "narammala": "narammala",
    "nikaweratiya": "nikaweratiya",
    "pannala": "pannala",
    "polgahawela": "polgahawela",
    "walikatiya": "walikatiya",
    "kirindiwela": "kirindiwela",
    "kalagedihena": "kalagedihena",
    "biyagama": "biyagama",
    "wariyapola": "wariyapola",
    "gonawala": "gonawala",
    "mannar": "mannar",
    "dompe": "dompe",
    "mannar city": "mannar-43",
    "mannar-43": "mannar-43",
    "pugoda": "pugoda",
    "moonamale": "moonamale",
    "nilsirigama": "nilsirigama",
    "matale": "matale",
    "miriswatta": "miriswatta",
    "dambulla": "dambulla",
    "galewela": "galewela",
    "matale city": "matale-22",
    "matale-22": "matale-22",
    "rattota": "rattota",
    "ukuwela": "ukuwela",
    "yatawatta": "yatawatta",
    "matara": "matara",
    "akuressa": "akuressa",
    "dikwella": "dikwella",
    "hakmana": "hakmana",
    "kamburupitiya": "kamburupitiya",
    "weligama": "weligama",
    "kadihingala": "kadihingala",
    "monaragala": "monaragala",
    "bibile": "bibile",
    "buttala": "buttala",
    "kataragama": "kataragama",
    "monaragala city": "monaragala-82",
    "monaragala-82": "monaragala-82",
    "wellawaya": "wellawaya",
    "mullativu": "mullativu",
    "nuwara eliya": "nuwara-eliya",
    "nuwara-eliya": "nuwara-eliya",
    "nuwara eliya city": "nuwara-eliya-23",
    "nuwara-eliya-23": "nuwara-eliya-23",
    "kotmale": "kotmale",
    "polonnaruwa": "polonnaruwa",
    "udapalatha": "udapalatha",
    "walapane": "walapane",
    "hingurakgoda": "hingurakgoda",
    "arukwatta": "arukwatta",
    "medirigiriya": "medirigiriya",
    "ramboda": "ramboda",
    "rikillagaskada": "rikillagaskada",
    "puttalam": "puttalam",
    "karametiya": "karametiya",
    "chilaw": "chilaw",
    "dankotuwa": "dankotuwa",
    "nattandiya": "nattandiya",
    "puttalam city": "puttalam-62",
    "puttalam-62": "puttalam-62",
    "wennappuwa": "wennappuwa",
    "ratnapura": "ratnapura",
    "balangoda": "balangoda",
    "eheliyagoda": "eheliyagoda",
    "embilipitiya": "embilipitiya",
    "kuruwita": "kuruwita",
    "pelmadulla": "pelmadulla",
    "ratnapura city": "ratnapura-91",
    "ratnapura-91": "ratnapura-91",
    "kahawatta": "kahawatta",
    "trincomalee": "trincomalee",
    "madalagama": "madalagama",
    "watapotha": "watapotha",
    "nivithigala": "nivithigala",
    "kinniya": "kinniya",
    "karawita": "karawita",
    "botiyatenna": "botiyatenna",
    "weddagala": "weddagala",
    "trincomalee city": "trincomalee-53",
    "trincomalee-53": "trincomalee-53",
    "vavuniya": "vavuniya",
    "eppawala": "eppawala",
    "habarana": "habarana",
    "diyatalawa": "diyatalawa",
    "saudi arabia": "saudi-arabia",
    "saudi-arabia": "saudi-arabia",
    "riyadh": "riyadh",
    "buridah": "buridah",
    "ha'il": "hail",
    "hail": "hail",
    "dammam": "dammam",
    "makkah": "makkah",
    "madinah": "madinah",
    "arar": "arar",
    "skakah": "skakah",
    "tabuk": "tabuk",
    "albaha": "albaha",
    "abha": "abha",
    "jazan": "jazan",
    "najran": "najran",
    "angoda": "angoda",
    "avissawella": "avissawella",
    "godagama": "godagama",
    "meegoda": "meegoda",
    "kohuwala": "kohuwala",
    "kotte": "kotte",
    "talawatugoda": "talawatugoda",
    "wellampitiya": "wellampitiya",
    "kotikawatta": "kotikawatta",
    "ahangama": "ahangama",
    "kalubowila": "kalubowila",
    "polgasowita": "polgasowita",
    "olaboduwa": "olaboduwa",
    "embulgama": "embulgama",
    "ranala": "ranala",
    "nawagamuwa": "nawagamuwa",
    "batapola": "batapola",
    "galle city": "galle-31",
    "galle-31": "galle-31",
    "united arab emirates": "united-arab-emirates",
    "united-arab-emirates": "united-arab-emirates",
    "abu dhabi": "abu-dhabi",
    "abu-dhabi": "abu-dhabi",
    "dubai": "dubai",
    "sharjah": "sharjah",
    "ajman": "ajman",
    "umm al quwain": "umm-al-quwain",
    "umm-al-quwain": "umm-al-quwain",
    "ras al khaimah": "ras-al-khaimah",
    "ras-al-khaimah": "ras-al-khaimah",
    "fujairah": "fujairah",
    "karapitiya": "karapitiya",
    "ahungalla": "ahungalla",
    "balapitiya": "balapitiya",
    "atakohota": "atakohota",
    "uragasmanhandiya": "uragasmanhandiya",
    "karandeniya": "karandeniya",
    "neluwa": "neluwa",
    "opatha": "opatha",
    "thangalla": "thangalla",
    "kosgoda": "kosgoda",
    "delgoda": "delgoda",
    "ganemulla": "ganemulla",
    "kadawatha": "kadawatha",
    "kandana": "kandana",
    "katunayake": "katunayake",
    "nittambuwa": "nittambuwa",
    "ragama": "ragama",
    "veyangoda": "veyangoda",
    "seeduwa": "seeduwa",
    "alutgama": "alutgama",
    "ampitiya": "ampitiya",
    "digana": "digana",
    "galagedara": "galagedara",
    "gampola": "gampola",
    "gelioya": "gelioya",
    "kadugannawa": "kadugannawa",
    "katugastota": "katugastota",
    "madawala bazaar": "madawala-bazaar",
    "madawala-bazaar": "madawala-bazaar",
    "nawalapitiya": "nawalapitiya",
    "peradeniya": "peradeniya",
    "pilimatalawa": "pilimatalawa",
    "wattegama": "wattegama",
    "pallekele": "pallekele",
    "danthure": "danthure",
    "rattapitiya": "rattapitiya",
    "dodamwala": "dodamwala",
    "poththapitiya": "poththapitiya",
    "udunuwara": "udunuwara",
    "galaha": "galaha",
    "deltota": "deltota",
    "pathahewaheta": "pathahewaheta",
    "doluwa": "doluwa",
    "pussellawa": "pussellawa",
    "tawalantenne": "tawalantenne",
    "urapola": "urapola",
    "kitulgala": "kitulgala",
    "giriulla": "giriulla",
    "hettipola": "hettipola",
    "palapathwela": "palapathwela",
    "sigiriya": "sigiriya",
    "pallepola": "pallepola",
    "deniyaya": "deniyaya",
    "kamburugamuwa": "kamburugamuwa",
    "kekanadurra": "kekanadurra",
    "matara city": "matara-32",
    "matara-32": "matara-32",
    "gandara": "gandara",
    "menikhinna": "menikhinna",
    "mullativu city": "mullativu-45",
    "mullativu-45": "mullativu-45",
    "ginigathhena": "ginigathhena",
    "hatton": "hatton",
    "madulla": "madulla",
    "kaduruwela": "kaduruwela",
    "polonnaruwa city": "polonnaruwa-72",
    "polonnaruwa-72": "polonnaruwa-72",
    "marawila": "marawila",
    "anamaduwa": "anamaduwa",
    "kilinochchi city": "kilinochchi-42",
    "kilinochchi-42": "kilinochchi-42",
    "kuliyapitiya": "kuliyapitiya",
    "vavuniya city": "vavuniya-44",
    "vavuniya-44": "vavuniya-44",
    "sri lanka": "sri-lanka",
    "sri-lanka": "sri-lanka"
}


def resolve_ikman_location_slug(keyword: Optional[str]) -> Optional[str]:
    """
    Resolves a location keyword or suburb name to a native Ikman location slug.
    Returns the slug (e.g., 'dehiwala', 'colombo-6', 'rajagiriya') if matched,
    or None if the keyword should fall back to a full-text query.
    """
    if not keyword or not keyword.strip():
        return None

    cleaned = keyword.strip().lower()

    # 1. Check known aliases & misspellings
    if cleaned in IKMAN_LOCATION_ALIASES:
        return IKMAN_LOCATION_ALIASES[cleaned]

    # 2. Check direct name or slug match in official Ikman locations
    if cleaned in IKMAN_LOCATIONS:
        return IKMAN_LOCATIONS[cleaned]

    # 3. Try hyphenated version
    hyphenated = cleaned.replace(" ", "-")
    if hyphenated in IKMAN_LOCATIONS:
        return IKMAN_LOCATIONS[hyphenated]

    return None
