"""fastapi users

Revision ID: c79432675333
Revises: ef1ea2454784
Create Date: 2026-09-19 23:59:08.891272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c79432675333'
down_revision: Union[str, Sequence[str], None] = 'ef1ea2454784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_sessions', sa.Column('token', sa.String(length=43), nullable=False))
    op.drop_index(op.f('ix_staff_sessions_expires_at'), table_name='staff_sessions')
    op.drop_index(op.f('ix_staff_sessions_token_hash'), table_name='staff_sessions')
    op.drop_index(op.f('ix_staff_sessions_user_id'), table_name='staff_sessions')
    op.create_index(op.f('ix_staff_sessions_created_at'), 'staff_sessions', ['created_at'], unique=False)
    op.drop_column('staff_sessions', 'revoked_at')
    op.drop_column('staff_sessions', 'expires_at')
    op.drop_column('staff_sessions', 'token_hash')
    op.drop_column('staff_sessions', 'id')
    op.add_column('staff_users', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('staff_users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('staff_users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('staff_users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_users', sa.Column('password_hash', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('staff_users', 'is_verified')
    op.drop_column('staff_users', 'is_superuser')
    op.drop_column('staff_users', 'hashed_password')
    op.add_column('staff_sessions', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('staff_sessions', sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('staff_sessions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('staff_sessions', sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_staff_sessions_created_at'), table_name='staff_sessions')
    op.create_index(op.f('ix_staff_sessions_user_id'), 'staff_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_staff_sessions_token_hash'), 'staff_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_staff_sessions_expires_at'), 'staff_sessions', ['expires_at'], unique=False)
    op.drop_column('staff_sessions', 'token')
    # ### end Alembic commands ###
