"""Add location cache and prospect coords

Revision ID: 618d8e137a9a
Revises: aeffbea281b5
Create Date: 2026-09-27 02:31:15.472302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618d8e137a9a'
down_revision: Union[str, Sequence[str], None] = 'aeffbea281b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_cache',
    sa.Column('location_string', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('location_string', name=op.f('pk_location_cache'))
    )
    op.add_column('prospects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('prospects', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'longitude')
    op.drop_column('prospects', 'latitude')
    op.drop_table('location_cache')
    # ### end Alembic commands ###
