"""create chat tables

PROJECT_OVERVIEW.md §4's `conversations`, `messages`, and `leads`, with three deliberate
additions: `messages.seq`, `messages.tool_payload`, and `leads.updated_at`. See
context/chores/chat-schema/spec.md for why each one earns its place.

`seq` is the ordering key for a conversation, not `created_at`: one pass of the agent loop
writes several turns inside a single transaction, and Postgres now() is transaction-start
time, so those rows share a timestamp.

Tables are created conversations-first and dropped in reverse, because both foreign keys
point at it. `messages.role`'s CHECK constraint is not listed separately — it rides along
inside the CREATE TABLE, from `Enum(native_enum=False, create_constraint=True)`.

Revision ID: 388fdda07622
Revises: da5c830b686e
Create Date: 2026-08-17 16:31:23.110673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388fdda07622'
down_revision: Union[str, Sequence[str], None] = 'da5c830b686e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_leads_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_leads_conversation_id'))
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'tool', name='message_role', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_payload', sa.JSON(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'seq', name=op.f('uq_messages_conversation_id'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
