"""add_property_contacts

Revision ID: 612bb699c217
Revises: c79432675333
Create Date: 2026-09-20 16:41:29.682418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612bb699c217'
down_revision: Union[str, Sequence[str], None] = 'c79432675333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_type', sa.Enum('owner', 'broker', name='property_contact_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_contacts'))
    )
    op.create_index(op.f('ix_property_contacts_contact_type'), 'property_contacts', ['contact_type'], unique=False)
    op.create_table('property_contact_phones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_contact_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('is_whatsapp', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['property_contact_id'], ['property_contacts.id'], name=op.f('fk_property_contact_phones_property_contact_id_property_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_contact_phones'))
    )
    op.create_index(op.f('ix_property_contact_phones_property_contact_id'), 'property_contact_phones', ['property_contact_id'], unique=False)
    op.add_column('properties', sa.Column('property_contact_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_properties_property_contact_id'), 'properties', ['property_contact_id'], unique=False)
    op.create_foreign_key(op.f('fk_properties_property_contact_id_property_contacts'), 'properties', 'property_contacts', ['property_contact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_properties_ck_properties_listing_type'), 'properties', "listing_type::text = ANY (ARRAY['sale'::character varying, 'rent'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_properties_ck_properties_furnishing_status'), 'properties', "furnishing_status::text = ANY (ARRAY['unfurnished'::character varying, 'semi_furnished'::character varying, 'fully_furnished'::character varying]::text[])")
    op.drop_constraint(op.f('fk_properties_property_contact_id_property_contacts'), 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_property_contact_id'), table_name='properties')
    op.create_index(op.f('ix_properties_location_geography'), 'properties', [sa.literal_column('(st_setsrid(st_makepoint(longitude, latitude), 4326)::geography)')], unique=False, postgresql_using='gist', postgresql_where='((latitude IS NOT NULL) AND (longitude IS NOT NULL))')
    op.alter_column('properties', 'furnishing_status',
               existing_type=sa.Enum('unfurnished', 'semi_furnished', 'fully_furnished', name='furnishing_status', native_enum=False, create_constraint=True, length=16),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    op.alter_column('properties', 'listing_type',
               existing_type=sa.Enum('sale', 'rent', name='listing_type', native_enum=False, create_constraint=True, length=16),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.drop_column('properties', 'property_contact_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_property_contact_phones_property_contact_id'), table_name='property_contact_phones')
    op.drop_table('property_contact_phones')
    op.drop_index(op.f('ix_property_contacts_contact_type'), table_name='property_contacts')
    op.drop_table('property_contacts')
    # ### end Alembic commands ###
