"""add site config display toggles

Revision ID: 4ebe8366a842
Revises: e6a2054db28a
Create Date: 2026-09-20 20:04:36.372087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebe8366a842'
down_revision: Union[str, Sequence[str], None] = 'e6a2054db28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_configurations', sa.Column('show_phone_numbers', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_configurations', sa.Column('show_contact_email', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_configurations', sa.Column('show_instagram_link', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_configurations', sa.Column('show_facebook_link', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_configurations', sa.Column('show_x_link', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_configurations', sa.Column('show_tiktok_link', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_configurations', sa.Column('show_city', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_configurations', 'show_city')
    op.drop_column('site_configurations', 'show_tiktok_link')
    op.drop_column('site_configurations', 'show_x_link')
    op.drop_column('site_configurations', 'show_facebook_link')
    op.drop_column('site_configurations', 'show_instagram_link')
    op.drop_column('site_configurations', 'show_contact_email')
    op.drop_column('site_configurations', 'show_phone_numbers')
    # ### end Alembic commands ###

