"""add leads.intent

Which side of the transaction a lead is on — buy, rent, or sell. Added when the agent
persona grew a seller lane; the alternative was a substring search over the free-text
`preferences` blob. Nullable, because guessing intent wrong is worse than leaving it unset.

**The CHECK constraint is emitted, and this was verified rather than assumed.** The worry
going in was that `op.add_column` would drop the `_type_bound` CHECK that
`Enum(native_enum=False, create_constraint=True)` attaches — the two earlier migrations
got theirs free inside `CREATE TABLE`, and ALTER TABLE ADD COLUMN does not generally carry
table-level constraints. On Alembic 1.19 + SQLAlchemy 2.0 it does: after this upgrade Neon
holds `ck_leads_lead_intent` with `IN ('buy','rent','sell')`, and an insert of `'banana'`
raises CheckViolation. So no explicit `op.create_check_constraint` is needed here — but
check the catalog, not just the column, if this pattern is repeated.

A follow-up `--autogenerate` after this ran came back empty, confirming that
`alembic/env.py`'s `_type_bound_check_names()` picked the new constraint up on its own
(it collects from the models rather than hardcoding names).

`downgrade()` drops the column, and Postgres drops the CHECK with it.

Revision ID: c9432564c721
Revises: 388fdda07622
Create Date: 2026-08-18 20:25:34.109806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9432564c721'
down_revision: Union[str, Sequence[str], None] = '388fdda07622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('intent', sa.Enum('buy', 'rent', 'sell', name='lead_intent', native_enum=False, create_constraint=True, length=16), nullable=True))
    op.create_index(op.f('ix_leads_intent'), 'leads', ['intent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_intent'), table_name='leads')
    op.drop_column('leads', 'intent')
    # ### end Alembic commands ###
