"""create properties table

PROJECT_OVERVIEW.md §4 with one deliberate addition: `image_alt`. Alt text describes
the photograph rather than the listing, so it cannot be derived from `title`.

`property_type` and `status` are VARCHAR + named CHECK, not native Postgres ENUM, so
adding a member later is an ordinary migration instead of an ALTER TYPE.

Revision ID: da5c830b686e
Revises:
Create Date: 2026-08-09 01:41:55.326664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da5c830b686e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('property_type', sa.Enum('house', 'apartment', 'land', 'commercial', name='property_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('image_alt', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('available', 'under_offer', 'sold', name='property_status', native_enum=False, create_constraint=True, length=16), server_default='available', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_location'), 'properties', ['location'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_location'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
