"""Add SiteConfiguration table

Revision ID: e6a2054db28a
Revises: 612bb699c217
Create Date: 2026-09-20 18:49:25.664850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a2054db28a'
down_revision: Union[str, Sequence[str], None] = '612bb699c217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_configurations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_numbers', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('instagram_link', sa.String(length=255), nullable=True),
    sa.Column('facebook_link', sa.String(length=255), nullable=True),
    sa.Column('x_link', sa.String(length=255), nullable=True),
    sa.Column('tiktok_link', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('extra_settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_configurations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_configurations')
    # ### end Alembic commands ###
