"""Add scanner settings to site configuration

Revision ID: aeffbea281b5
Revises: 2da8079da5db
Create Date: 2026-09-26 18:51:47.448304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeffbea281b5'
down_revision: Union[str, Sequence[str], None] = '2da8079da5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_configurations', sa.Column('scanner_settings', sa.JSON(), server_default=sa.text('\'{"enabled": false, "frequency_hours": 24, "pages_to_scan": 5, "property_types": ["house", "apartment"]}\''), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_configurations', 'scanner_settings')
    # ### end Alembic commands ###
