"""Add interested_property_id to Lead

Revision ID: 5f56afc125ca
Revises: 618d8e137a9a
Create Date: 2026-09-27 02:46:56.925870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f56afc125ca'
down_revision: Union[str, Sequence[str], None] = '618d8e137a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('interested_property_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_leads_interested_property_id'), 'leads', ['interested_property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_interested_property_id'), table_name='leads')
    op.drop_column('leads', 'interested_property_id')
    # ### end Alembic commands ###
