"""add scan job created_by

Revision ID: 38807aff87a5
Revises: f282e08f5c4f
Create Date: 2026-09-24 02:45:42.777398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '38807aff87a5'
down_revision: Union[str, Sequence[str], None] = 'f282e08f5c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('created_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.add_column('scan_jobs', sa.Column('created_by_name', sa.String(length=120), nullable=True))
    op.create_foreign_key(op.f('fk_scan_jobs_created_by_id_staff_users'), 'scan_jobs', 'staff_users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scan_jobs_created_by_id_staff_users'), 'scan_jobs', type_='foreignkey')
    op.drop_column('scan_jobs', 'created_by_name')
    op.drop_column('scan_jobs', 'created_by_id')
    # ### end Alembic commands ###
