"""add_prospects

Revision ID: ac1cae493e7a
Revises: 9cfe4d90e62e
Create Date: 2026-09-21 02:06:46.948374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac1cae493e7a'
down_revision: Union[str, Sequence[str], None] = '9cfe4d90e62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ikman_ad_id', sa.String(length=64), nullable=False),
    sa.Column('ikman_url', sa.Text(), nullable=False),
    sa.Column('ikman_slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('property_type', sa.String(length=64), nullable=False),
    sa.Column('listing_type', sa.String(length=32), nullable=False),
    sa.Column('poster_name', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('classification_reasons', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('classification_method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('is_auth_dealer', sa.Boolean(), nullable=False),
    sa.Column('membership_level', sa.String(length=16), nullable=False),
    sa.Column('shop_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prospects'))
    )
    op.create_index(op.f('ix_prospects_ikman_ad_id'), 'prospects', ['ikman_ad_id'], unique=True)

    op.add_column('site_configurations', sa.Column('prospect_retention_days', sa.Integer(), server_default=sa.text('30'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_configurations', 'prospect_retention_days')

    op.drop_index(op.f('ix_prospects_ikman_ad_id'), table_name='prospects')
    op.drop_table('prospects')
    # ### end Alembic commands ###
